export { default as ShuttleBusPage } from './Setup/ShuttleBusPage/ShuttleBusPage';
export { default as FoodistPage } from './FoodistPage/FoodistPage';
export { default as WorkingTimePage } from './WorkingTime/WorkingTimePage/WorkingTimePage';
export { default as NewWorkingTimePage } from './WorkingTime/NewWorkingTimePage/NewWorkingTimePage';
export { default as InfoPage } from './Setup/InfoPage/InfoPage';
export { default as FoodistUploadPage } from './Setup/FoodistUploadPage/FoodistUploadPage';
export { default as VisitorPage } from './Setup/Visitor/Visitor';
export { default as WorkingTimeRoot } from './WorkingTime/WorkingTimeRoot/WorkingTimeRoot';
export { default as SettingsPage } from './Setup/Settings/Settings';
export { default as NewsPage } from './News/News'
